name: Auto Create PR on new push

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - 'main'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            if (branch === 'main') {
              console.log('Main branch push detected, skipping PR creation.');
              return;
            }

            // Check if a PR from this branch to main already exists
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              base: 'main',
              state: 'open',
            });

            if (pulls.length === 0) {
              // Create a new pull request
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: branch,
                base: 'main',
                title: `Auto PR: Changes from ${branch}`,
                body: `This PR includes the changes from ${branch}.`,
                labels: ['auto-generated'],
              });
              console.log(`Created PR from ${branch} to main.`);
            } else {
              console.log(`PR from ${branch} to main already exists.`);
            }