name: Auto Pull on Merge

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and pull latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ./tier_list_app
            git pull origin main
            pkill -9 ruby
            pkill -9 ruby
            set -o errexit
            bundle install
            bundle exec rails assets:precompile RAILS_ENV=production
            bundle exec rails assets:clean RAILS_ENV=production
            bundle exec rails db:migrate RAILS_ENV=production
            nohup env RAILS_ENV=production bundle exec puma -C config/puma.rb > puma.log 2>&1 &